version: '3.3'
services:
  backend:
    image: dto80/se234-lab12
    ports:
      - 8999:8080
    volumes:
      - type: bind
        source: /home/ubuntu/temp/assets/
        target: /data
  fontend:
    image: pattaradanai888/automate-test
    ports:
      - 8199:80
